"use strict";
exports.__esModule = true;
exports.SERVER_PROXY = exports.CORS_ORIGIN = exports.TASK_TICK_INTERVAL_MS = exports.PLAYGROUND = exports.ALLOW_INTROSPECTION = exports.DEBUG = exports.TOKEN_EXPIRY_TIME = exports.VAPID_PUBLIC_KEY = exports.VAPID_PRIVATE_KEY = exports.APP_PRIVATE_KEY = exports.PORT = exports.ENDPOINT = void 0;
// import * as dotenv from 'dotenv';
var env = require("env-var");
// dotenv.config();
var ENDPOINT = env.get('PRISMA_ENDPOINT').required().asUrlString();
exports.ENDPOINT = ENDPOINT;
var PORT = env.get('SERVER_PORT').required().asString();
exports.PORT = PORT;
// const API_SECRET = env.get('PRISMA_MANAGEMENT_API_SECRET').asString();
var APP_PRIVATE_KEY = env.get('APP_PRIVATE_KEY').asString();
exports.APP_PRIVATE_KEY = APP_PRIVATE_KEY;
var VAPID_PUBLIC_KEY = env.get('VAPID_PUBLIC_KEY').asString();
exports.VAPID_PUBLIC_KEY = VAPID_PUBLIC_KEY;
var VAPID_PRIVATE_KEY = env.get('VAPID_PRIVATE_KEY').asString();
exports.VAPID_PRIVATE_KEY = VAPID_PRIVATE_KEY;
var TOKEN_EXPIRY_TIME = env.get('TOKEN_EXPIRY_TIME').asString();
exports.TOKEN_EXPIRY_TIME = TOKEN_EXPIRY_TIME;
var DEBUG = env.get('DEBUG').asBool();
exports.DEBUG = DEBUG;
var ALLOW_INTROSPECTION = env.get('ALLOW_INTROSPECTION').asBool();
exports.ALLOW_INTROSPECTION = ALLOW_INTROSPECTION;
var PLAYGROUND = env.get('PLAYGROUND').asBool();
exports.PLAYGROUND = PLAYGROUND;
var TASK_TICK_INTERVAL_MS = env.get('TASK_TICK_INTERVAL_MS').asIntPositive();
exports.TASK_TICK_INTERVAL_MS = TASK_TICK_INTERVAL_MS;
var CORS_ORIGIN = env.get('CORS_ORIGIN').asString();
exports.CORS_ORIGIN = CORS_ORIGIN;
var SERVER_PROXY = env.get('SERVER_PROXY').asString();
exports.SERVER_PROXY = SERVER_PROXY;
